### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by Maria-C** [ceciliafesti/AED#2]
- Hay un archivo ejecutable en el repositorio, no debería estar subido.
- Hay tres archivos .txt en el repositorio, deberías eliminar los que no correspondan.

Saludos

**Comment by Maria-C** [comment]
Además deberías renombrar los repositorios como se pidió en clase. "TP 0", "TP 1", etc.

Saludos

**Comment by ceciliafesti** [comment]
Ya hice los cambios solicitados 

Saludos

**Comment by Maria-C** [comment]
Listo, TP aprobado.
Saludos.
